### ISSUE TITLE
[BUG] "ReferenceError: method is not defined" from 2.5.5+

### ISSUE THREAD

**Issue by jwlawrence** [microsoft/ApplicationInsights-JS#1402]
**Description/Screenshot**
When I attempt to use the client side tracking code introduced in 2.5.5 and higher I'm seeing a reference error:
`Uncaught (in promise) ReferenceError: method is not defined`

This seems to be the offending code:
`method = "onerror", t(["_" + method]);`

**Steps to Reproduce**

Attempt to load the SDK using the script tag using v2.5.5 or higher and watch the world burn.

 - OS/Browser: MacOS 10.15.7, Chrome 86.0.4240.75
 - SDK Version [e.g. 22]: 2.5.5 and up
 - How you initialized the SDK: Script tag

**Expected behavior**
SDK to load without errors

**Additional context**
This is running within an Ember addon dummy app. All that really means is that it's a page with no content used purely for testing and served via node.js.

**Comment by MSNev** [comment]
Hi @jwlawrence,

I think you will find that this was an issue with version 3 of the snippet which was fixed in version 4 (as part of #1283 and fixed with #1286)

Look in the snippet code that you are using for the "sv" value, if it's 3 then that is the issue and just copy the current version.

This is a sample of where to find the snippet version
m={initialize:!0,queue:[],__sv:"4"__,version:2,config:d};

The current version is on the readme and the checked in version is here 
https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/snippet/snippet.min.js

**Comment by MSNev** [comment]
And I think the reason you are seeing this from v2.5.5+ is because of the new uncaught promise handling config value, which *should* be defaulting to false but I'm guessing that you have enabled.

```enableUnhandledPromiseRejectionTracking```

**Comment by jwlawrence** [comment]
Thanks for the quick reply @MSNev but unfortunately I'm still seeing this error. I'm using the code you linked above and still see the error. I also explicitly set the `enableUnhandledPromiseRejectionTracking` prop to false and still get it. When I switch back to the legacy tracking code it works no problem.

**Comment by jwlawrence** [comment]
Also worth noting that running the older script through eslint produces no errors where the new script throws quite a few including lots of undefined errors: https://eslint.org/demo#eyJ0ZXh0IjoiIShmdW5jdGlvbiAoVCwgbCwgeSkge1xuICAgICAgdmFyIFMgPSBULmxvY2F0aW9uLFxuICAgICAgICB1ID0gXCJzY3JpcHRcIixcbiAgICAgICAgayA9IFwiaW5zdHJ1bWVudGF0aW9uS2V5XCIsXG4gICAgICAgIEQgPSBcImluZ2VzdGlvbmVuZHBvaW50XCIsXG4gICAgICAgIEMgPSBcImRpc2FibGVFeGNlcHRpb25UcmFja2luZ1wiLFxuICAgICAgICBFID0gXCJhaS5kZXZpY2UuXCIsXG4gICAgICAgIEkgPSBcInRvTG93ZXJDYXNlXCIsXG4gICAgICAgIGIgPSBcImNyb3NzT3JpZ2luXCIsXG4gICAgICAgIHcgPSBcIlBPU1RcIixcbiAgICAgICAgZSA9IFwiYXBwSW5zaWdodHNTREtcIixcbiAgICAgICAgdCA9IHkubmFtZSB8fCBcImFwcEluc2lnaHRzXCI7XG4gICAgICAoeS5uYW1lIHx8IFRbZV0pICYmIChUW2VdID0gdCk7XG4gICAgICB2YXIgbiA9XG4gICAgICAgIFRbdF0gfHxcbiAgICAgICAgKGZ1bmN0aW9uIChkKSB7XG4gICAgICAgICAgdmFyIGcgPSAhMSxcbiAgICAgICAgICAgIGYgPSAhMSxcbiAgICAgICAgICAgIG0gPSB7IGluaXRpYWxpemU6ICEwLCBxdWV1ZTogW10sIHN2OiBcIjRcIiwgdmVyc2lvbjogMiwgY29uZmlnOiBkIH07XG4gICAgICAgICAgZnVuY3Rpb24gdihlLCB0KSB7XG4gICAgICAgICAgICB2YXIgbiA9IHt9LFxuICAgICAgICAgICAgICBhID0gXCJCcm93c2VyXCI7XG4gICAgICAgICAgICByZXR1cm4gKFxuICAgICAgICAgICAgICAobltFICsgXCJpZFwiXSA9IGFbSV0oKSksXG4gICAgICAgICAgICAgIChuW0UgKyBcInR5cGVcIl0gPSBhKSxcbiAgICAgICAgICAgICAgKG5bXCJhaS5vcGVyYXRpb24ubmFtZVwiXSA9IChTICYmIFMucGF0aG5hbWUpIHx8IFwiX3Vua25vd25fXCIpLFxuICAgICAgICAgICAgICAobltcImFpLmludGVybmFsLnNka1ZlcnNpb25cIl0gPVxuICAgICAgICAgICAgICAgIFwiamF2YXNjcmlwdDpzbmlwcGV0X1wiICsgKG0uc3YgfHwgbS52ZXJzaW9uKSksXG4gICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICB0aW1lOiAoZnVuY3Rpb24gKCkge1xuICAgICAgICAgICAgICAgICAgdmFyIGUgPSBuZXcgRGF0ZSgpO1xuICAgICAgICAgICAgICAgICAgZnVuY3Rpb24gdChlKSB7XG4gICAgICAgICAgICAgICAgICAgIHZhciB0ID0gXCJcIiArIGU7XG4gICAgICAgICAgICAgICAgICAgIHJldHVybiAxID09PSB0Lmxlbmd0aCAmJiAodCA9IFwiMFwiICsgdCksIHQ7XG4gICAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgICByZXR1cm4gKFxuICAgICAgICAgICAgICAgICAgICBlLmdldFVUQ0Z1bGxZZWFyKCkgK1xuICAgICAgICAgICAgICAgICAgICBcIi1cIiArXG4gICAgICAgICAgICAgICAgICAgIHQoMSArIGUuZ2V0VVRDTW9udGgoKSkgK1xuICAgICAgICAgICAgICAgICAgICBcIi1cIiArXG4gICAgICAgICAgICAgICAgICAgIHQoZS5nZXRVVENEYXRlKCkpICtcbiAgICAgICAgICAgICAgICAgICAgXCJUXCIgK1xuICAgICAgICAgICAgICAgICAgICB0KGUuZ2V0VVRDSG91cnMoKSkgK1xuICAgICAgICAgICAgICAgICAgICBcIjpcIiArXG4gICAgICAgICAgICAgICAgICAgIHQoZS5nZXRVVENNaW51dGVzKCkpICtcbiAgICAgICAgICAgICAgICAgICAgXCI6XCIgK1xuICAgICAgICAgICAgICAgICAgICB0KGUuZ2V0VVRDU2Vjb25kcygpKSArXG4gICAgICAgICAgICAgICAgICAgIFwiLlwiICtcbiAgICAgICAgICAgICAgICAgICAgKChlLmdldFVUQ01pbGxpc2Vjb25kcygpIC8gMWUzKS50b0ZpeGVkKDMpICsgXCJcIikuc2xpY2UoXG4gICAgICAgICAgICAgICAgICAgICAgMixcbiAgICAgICAgICAgICAgICAgICAgICA1XG4gICAgICAgICAgICAgICAgICAgICkgK1xuICAgICAgICAgICAgICAgICAgICBcIlpcIlxuICAgICAgICAgICAgICAgICAgKTtcbiAgICAgICAgICAgICAgICB9KSgpLFxuICAgICAgICAgICAgICAgIGlLZXk6IGUsXG4gICAgICAgICAgICAgICAgbmFtZTpcbiAgICAgICAgICAgICAgICAgIFwiTWljcm9zb2Z0LkFwcGxpY2F0aW9uSW5zaWdodHMuXCIgK1xuICAgICAgICAgICAgICAgICAgZS5yZXBsYWNlKC8tL2csIFwiXCIpICtcbiAgICAgICAgICAgICAgICAgIFwiLlwiICtcbiAgICAgICAgICAgICAgICAgIHQsXG4gICAgICAgICAgICAgICAgc2FtcGxlUmF0ZTogMTAwLFxuICAgICAgICAgICAgICAgIHRhZ3M6IG4sXG4gICAgICAgICAgICAgICAgZGF0YTogeyBiYXNlRGF0YTogeyB2ZXI6IDIgfSB9LFxuICAgICAgICAgICAgICB9XG4gICAgICAgICAgICApO1xuICAgICAgICAgIH1cbiAgICAgICAgICB2YXIgaCA9IGQudXJsIHx8IHkuc3JjO1xuICAgICAgICAgIGlmIChoKSB7XG4gICAgICAgICAgICBmdW5jdGlvbiBhKGUpIHtcbiAgICAgICAgICAgICAgdmFyIHQsIG4sIGEsIGksIHIsIG8sIHMsIGMsIHAsIGwsIHU7XG4gICAgICAgICAgICAgIChnID0gITApLFxuICAgICAgICAgICAgICAgIChtLnF1ZXVlID0gW10pLFxuICAgICAgICAgICAgICAgIGYgfHxcbiAgICAgICAgICAgICAgICAgICgoZiA9ICEwKSxcbiAgICAgICAgICAgICAgICAgICh0ID0gaCksXG4gICAgICAgICAgICAgICAgICAocyA9IChmdW5jdGlvbiAoKSB7XG4gICAgICAgICAgICAgICAgICAgIHZhciBlID0ge30sXG4gICAgICAgICAgICAgICAgICAgICAgdCA9IGQuY29ubmVjdGlvblN0cmluZztcbiAgICAgICAgICAgICAgICAgICAgaWYgKHQpXG4gICAgICAgICAgICAgICAgICAgICAgZm9yICh2YXIgbiA9IHQuc3BsaXQoXCI7XCIpLCBhID0gMDsgYSA8IG4ubGVuZ3RoOyBhKyspIHtcbiAgICAgICAgICAgICAgICAgICAgICAgIHZhciBpID0gblthXS5zcGxpdChcIj1cIik7XG4gICAgICAgICAgICAgICAgICAgICAgICAyID09PSBpLmxlbmd0aCAmJiAoZVtpWzBdW0ldKCldID0gaVsxXSk7XG4gICAgICAgICAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgICAgICAgICBpZiAoIWVbRF0pIHtcbiAgICAgICAgICAgICAgICAgICAgICB2YXIgciA9IGUuZW5kcG9pbnRzdWZmaXgsXG4gICAgICAgICAgICAgICAgICAgICAgICBvID0gciA/IGUubG9jYXRpb24gOiBudWxsO1xuICAgICAgICAgICAgICAgICAgICAgIGVbRF0gPVxuICAgICAgICAgICAgICAgICAgICAgICAgXCJodHRwczovL1wiICtcbiAgICAgICAgICAgICAgICAgICAgICAgIChvID8gbyArIFwiLlwiIDogXCJcIikgK1xuICAgICAgICAgICAgICAgICAgICAgICAgXCJkYy5cIiArXG4gICAgICAgICAgICAgICAgICAgICAgICAociB8fCBcInNlcnZpY2VzLnZpc3VhbHN0dWRpby5jb21cIik7XG4gICAgICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGU7XG4gICAgICAgICAgICAgICAgICB9KSgpKSxcbiAgICAgICAgICAgICAgICAgIChjID0gc1trXSB8fCBkW2tdIHx8IFwiXCIpLFxuICAgICAgICAgICAgICAgICAgKHAgPSBzW0RdKSxcbiAgICAgICAgICAgICAgICAgIChsID0gcCA/IHAgKyBcIi92Mi90cmFja1wiIDogY29uZmlnLmVuZHBvaW50VXJsKSxcbiAgICAgICAgICAgICAgICAgICh1ID0gW10pLnB1c2goXG4gICAgICAgICAgICAgICAgICAgICgobiA9XG4gICAgICAgICAgICAgICAgICAgICAgXCJTREsgTE9BRCBGYWlsdXJlOiBGYWlsZWQgdG8gbG9hZCBBcHBsaWNhdGlvbiBJbnNpZ2h0cyBTREsgc2NyaXB0IChTZWUgc3RhY2sgZm9yIGRldGFpbHMpXCIpLFxuICAgICAgICAgICAgICAgICAgICAoYSA9IHQpLFxuICAgICAgICAgICAgICAgICAgICAoaSA9IGwpLFxuICAgICAgICAgICAgICAgICAgICAoKG8gPSAociA9IHYoYywgXCJFeGNlcHRpb25cIikpLmRhdGEpLmJhc2VUeXBlID1cbiAgICAgICAgICAgICAgICAgICAgICBcIkV4Y2VwdGlvbkRhdGFcIiksXG4gICAgICAgICAgICAgICAgICAgIChvLmJhc2VEYXRhLmV4Y2VwdGlvbnMgPSBbXG4gICAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgICAgdHlwZU5hbWU6IFwiU0RLTG9hZEZhaWxlZFwiLFxuICAgICAgICAgICAgICAgICAgICAgICAgbWVzc2FnZTogbi5yZXBsYWNlKC9cXC4vZywgXCItXCIpLFxuICAgICAgICAgICAgICAgICAgICAgICAgaGFzRnVsbFN0YWNrOiAhMSxcbiAgICAgICAgICAgICAgICAgICAgICAgIHN0YWNrOlxuICAgICAgICAgICAgICAgICAgICAgICAgICBuICtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgXCJcXG5TbmlwcGV0IGZhaWxlZCB0byBsb2FkIFtcIiArXG4gICAgICAgICAgICAgICAgICAgICAgICAgIGEgK1xuICAgICAgICAgICAgICAgICAgICAgICAgICBcIl0gLS0gVGVsZW1ldHJ5IGlzIGRpc2FibGVkXFxuSGVscCBMaW5rOiBodHRwczovL2dvLm1pY3Jvc29mdC5jb20vZndsaW5rLz9saW5raWQ9MjEyODEwOVxcbkhvc3Q6IFwiICtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgKChTICYmIFMucGF0aG5hbWUpIHx8IFwiX3Vua25vd25fXCIpICtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgXCJcXG5FbmRwb2ludDogXCIgK1xuICAgICAgICAgICAgICAgICAgICAgICAgICBpLFxuICAgICAgICAgICAgICAgICAgICAgICAgcGFyc2VkU3RhY2s6IFtdLFxuICAgICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICAgIF0pLFxuICAgICAgICAgICAgICAgICAgICByKVxuICAgICAgICAgICAgICAgICAgKSxcbiAgICAgICAgICAgICAgICAgIHUucHVzaChcbiAgICAgICAgICAgICAgICAgICAgKGZ1bmN0aW9uIChlLCB0LCBuLCBhKSB7XG4gICAgICAgICAgICAgICAgICAgICAgdmFyIGkgPSB2KGMsIFwiTWVzc2FnZVwiKSxcbiAgICAgICAgICAgICAgICAgICAgICAgIHIgPSBpLmRhdGE7XG4gICAgICAgICAgICAgICAgICAgICAgci5iYXNlVHlwZSA9IFwiTWVzc2FnZURhdGFcIjtcbiAgICAgICAgICAgICAgICAgICAgICB2YXIgbyA9IHIuYmFzZURhdGE7XG4gICAgICAgICAgICAgICAgICAgICAgcmV0dXJuIChcbiAgICAgICAgICAgICAgICAgICAgICAgIChvLm1lc3NhZ2UgPVxuICAgICAgICAgICAgICAgICAgICAgICAgICAnQUkgKEludGVybmFsKTogOTkgbWVzc2FnZTpcIicgK1xuICAgICAgICAgICAgICAgICAgICAgICAgICAoXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgXCJTREsgTE9BRCBGYWlsdXJlOiBGYWlsZWQgdG8gbG9hZCBBcHBsaWNhdGlvbiBJbnNpZ2h0cyBTREsgc2NyaXB0IChTZWUgc3RhY2sgZm9yIGRldGFpbHMpIChcIiArXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgbiArXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgXCIpXCJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgKS5yZXBsYWNlKC9cXFwiL2csIFwiXCIpICtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgJ1wiJyksXG4gICAgICAgICAgICAgICAgICAgICAgICAoby5wcm9wZXJ0aWVzID0geyBlbmRwb2ludDogYSB9KSxcbiAgICAgICAgICAgICAgICAgICAgICAgIGlcbiAgICAgICAgICAgICAgICAgICAgICApO1xuICAgICAgICAgICAgICAgICAgICB9KSgwLCAwLCB0LCBsKVxuICAgICAgICAgICAgICAgICAgKSxcbiAgICAgICAgICAgICAgICAgIChmdW5jdGlvbiAoZSwgdCkge1xuICAgICAgICAgICAgICAgICAgICBpZiAoSlNPTikge1xuICAgICAgICAgICAgICAgICAgICAgIHZhciBuID0gVC5mZXRjaDtcbiAgICAgICAgICAgICAgICAgICAgICBpZiAobiAmJiAheS51c2VYaHIpXG4gICAgICAgICAgICAgICAgICAgICAgICBuKHQsIHtcbiAgICAgICAgICAgICAgICAgICAgICAgICAgbWV0aG9kOiB3LFxuICAgICAgICAgICAgICAgICAgICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeShlKSxcbiAgICAgICAgICAgICAgICAgICAgICAgICAgbW9kZTogXCJjb3JzXCIsXG4gICAgICAgICAgICAgICAgICAgICAgICB9KTtcbiAgICAgICAgICAgICAgICAgICAgICBlbHNlIGlmIChYTUxIdHRwUmVxdWVzdCkge1xuICAgICAgICAgICAgICAgICAgICAgICAgdmFyIGEgPSBuZXcgWE1MSHR0cFJlcXVlc3QoKTtcbiAgICAgICAgICAgICAgICAgICAgICAgIGEub3Blbih3LCB0KSxcbiAgICAgICAgICAgICAgICAgICAgICAgICAgYS5zZXRSZXF1ZXN0SGVhZGVyKFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIFwiQ29udGVudC10eXBlXCIsXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgXCJhcHBsaWNhdGlvbi9qc29uXCJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgKSxcbiAgICAgICAgICAgICAgICAgICAgICAgICAgYS5zZW5kKEpTT04uc3RyaW5naWZ5KGUpKTtcbiAgICAgICAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgICAgICAgIH0pKHUsIGwpKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgICAgIGZ1bmN0aW9uIGkoZSwgdCkge1xuICAgICAgICAgICAgICBmIHx8XG4gICAgICAgICAgICAgICAgc2V0VGltZW91dChmdW5jdGlvbiAoKSB7XG4gICAgICAgICAgICAgICAgICAoIXQgJiYgbS5jb3JlKSB8fCBhKCk7XG4gICAgICAgICAgICAgICAgfSwgNTAwKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgICAgIHZhciBlID0gKGZ1bmN0aW9uICgpIHtcbiAgICAgICAgICAgICAgdmFyIG4gPSBsLmNyZWF0ZUVsZW1lbnQodSk7XG4gICAgICAgICAgICAgIG4uc3JjID0gaDtcbiAgICAgICAgICAgICAgdmFyIGUgPSB5W2JdO1xuICAgICAgICAgICAgICByZXR1cm4gKFxuICAgICAgICAgICAgICAgICghZSAmJiBcIlwiICE9PSBlKSB8fCBcInVuZGVmaW5lZFwiID09IG5bYl0gfHwgKG5bYl0gPSBlKSxcbiAgICAgICAgICAgICAgICAobi5vbmxvYWQgPSBpKSxcbiAgICAgICAgICAgICAgICAobi5vbmVycm9yID0gYSksXG4gICAgICAgICAgICAgICAgKG4ub25yZWFkeXN0YXRlY2hhbmdlID0gZnVuY3Rpb24gKGUsIHQpIHtcbiAgICAgICAgICAgICAgICAgIChcImxvYWRlZFwiICE9PSBuLnJlYWR5U3RhdGUgJiYgXCJjb21wbGV0ZVwiICE9PSBuLnJlYWR5U3RhdGUpIHx8XG4gICAgICAgICAgICAgICAgICAgIGkoMCwgdCk7XG4gICAgICAgICAgICAgICAgfSksXG4gICAgICAgICAgICAgICAgblxuICAgICAgICAgICAgICApO1xuICAgICAgICAgICAgfSkoKTtcbiAgICAgICAgICAgIHkubGQgPCAwXG4gICAgICAgICAgICAgID8gbC5nZXRFbGVtZW50c0J5VGFnTmFtZShcImhlYWRcIilbMF0uYXBwZW5kQ2hpbGQoZSlcbiAgICAgICAgICAgICAgOiBzZXRUaW1lb3V0KGZ1bmN0aW9uICgpIHtcbiAgICAgICAgICAgICAgICAgIGwuZ2V0RWxlbWVudHNCeVRhZ05hbWUodSlbMF0ucGFyZW50Tm9kZS5hcHBlbmRDaGlsZChlKTtcbiAgICAgICAgICAgICAgICB9LCB5LmxkIHx8IDApO1xuICAgICAgICAgIH1cbiAgICAgICAgICB0cnkge1xuICAgICAgICAgICAgbS5jb29raWUgPSBsLmNvb2tpZTtcbiAgICAgICAgICB9IGNhdGNoIChwKSB7fVxuICAgICAgICAgIGZ1bmN0aW9uIHQoZSkge1xuICAgICAgICAgICAgZm9yICg7IGUubGVuZ3RoOyApXG4gICAgICAgICAgICAgICEoZnVuY3Rpb24gKHQpIHtcbiAgICAgICAgICAgICAgICBtW3RdID0gZnVuY3Rpb24gKCkge1xuICAgICAgICAgICAgICAgICAgdmFyIGUgPSBhcmd1bWVudHM7XG4gICAgICAgICAgICAgICAgICBnIHx8XG4gICAgICAgICAgICAgICAgICAgIG0ucXVldWUucHVzaChmdW5jdGlvbiAoKSB7XG4gICAgICAgICAgICAgICAgICAgICAgbVt0XS5hcHBseShtLCBlKTtcbiAgICAgICAgICAgICAgICAgICAgfSk7XG4gICAgICAgICAgICAgICAgfTtcbiAgICAgICAgICAgICAgfSkoZS5wb3AoKSk7XG4gICAgICAgICAgfVxuICAgICAgICAgIHZhciBuID0gXCJ0cmFja1wiLFxuICAgICAgICAgICAgciA9IFwiVHJhY2tQYWdlXCIsXG4gICAgICAgICAgICBvID0gXCJUcmFja0V2ZW50XCI7XG4gICAgICAgICAgdChbXG4gICAgICAgICAgICBuICsgXCJFdmVudFwiLFxuICAgICAgICAgICAgbiArIFwiUGFnZVZpZXdcIixcbiAgICAgICAgICAgIG4gKyBcIkV4Y2VwdGlvblwiLFxuICAgICAgICAgICAgbiArIFwiVHJhY2VcIixcbiAgICAgICAgICAgIG4gKyBcIkRlcGVuZGVuY3lEYXRhXCIsXG4gICAgICAgICAgICBuICsgXCJNZXRyaWNcIixcbiAgICAgICAgICAgIG4gKyBcIlBhZ2VWaWV3UGVyZm9ybWFuY2VcIixcbiAgICAgICAgICAgIFwic3RhcnRcIiArIHIsXG4gICAgICAgICAgICBcInN0b3BcIiArIHIsXG4gICAgICAgICAgICBcInN0YXJ0XCIgKyBvLFxuICAgICAgICAgICAgXCJzdG9wXCIgKyBvLFxuICAgICAgICAgICAgXCJhZGRUZWxlbWV0cnlJbml0aWFsaXplclwiLFxuICAgICAgICAgICAgXCJzZXRBdXRoZW50aWNhdGVkVXNlckNvbnRleHRcIixcbiAgICAgICAgICAgIFwiY2xlYXJBdXRoZW50aWNhdGVkVXNlckNvbnRleHRcIixcbiAgICAgICAgICAgIFwiZmx1c2hcIixcbiAgICAgICAgICBdKSxcbiAgICAgICAgICAgIChtLlNldmVyaXR5TGV2ZWwgPSB7XG4gICAgICAgICAgICAgIFZlcmJvc2U6IDAsXG4gICAgICAgICAgICAgIEluZm9ybWF0aW9uOiAxLFxuICAgICAgICAgICAgICBXYXJuaW5nOiAyLFxuICAgICAgICAgICAgICBFcnJvcjogMyxcbiAgICAgICAgICAgICAgQ3JpdGljYWw6IDQsXG4gICAgICAgICAgICB9KTtcbiAgICAgICAgICB2YXIgcyA9IChkLmV4dGVuc2lvbkNvbmZpZyB8fCB7fSkuQXBwbGljYXRpb25JbnNpZ2h0c0FuYWx5dGljcyB8fCB7fTtcbiAgICAgICAgICBpZiAoITAgIT09IGRbQ10gJiYgITAgIT09IHNbQ10pIHtcbiAgICAgICAgICAgIChtZXRob2QgPSBcIm9uZXJyb3JcIiksIHQoW1wiX1wiICsgbWV0aG9kXSk7XG4gICAgICAgICAgICB2YXIgYyA9IFRbbWV0aG9kXTtcbiAgICAgICAgICAgIChUW21ldGhvZF0gPSBmdW5jdGlvbiAoZSwgdCwgbiwgYSwgaSkge1xuICAgICAgICAgICAgICB2YXIgciA9IGMgJiYgYyhlLCB0LCBuLCBhLCBpKTtcbiAgICAgICAgICAgICAgcmV0dXJuIChcbiAgICAgICAgICAgICAgICAhMCAhPT0gciAmJlxuICAgICAgICAgICAgICAgICAgbVtcIl9cIiArIG1ldGhvZF0oe1xuICAgICAgICAgICAgICAgICAgICBtZXNzYWdlOiBlLFxuICAgICAgICAgICAgICAgICAgICB1cmw6IHQsXG4gICAgICAgICAgICAgICAgICAgIGxpbmVOdW1iZXI6IG4sXG4gICAgICAgICAgICAgICAgICAgIGNvbHVtbk51bWJlcjogYSxcbiAgICAgICAgICAgICAgICAgICAgZXJyb3I6IGksXG4gICAgICAgICAgICAgICAgICB9KSxcbiAgICAgICAgICAgICAgICByXG4gICAgICAgICAgICAgICk7XG4gICAgICAgICAgICB9KSxcbiAgICAgICAgICAgICAgKGQuYXV0b0V4Y2VwdGlvbkluc3RydW1lbnRlZCA9ICEwKTtcbiAgICAgICAgICB9XG4gICAgICAgICAgcmV0dXJuIG07XG4gICAgICAgIH0pKHkuY2ZnKTtcbiAgICAgIChUW3RdID0gbikucXVldWUgJiYgMCA9PT0gbi5xdWV1ZS5sZW5ndGggJiYgbi50cmFja1BhZ2VWaWV3KHt9KTtcbiAgICB9KSh3aW5kb3csIGRvY3VtZW50LCB7XG4gICAgICBzcmM6IFwiaHR0cHM6Ly9hejQxNjQyNi52by5tc2VjbmQubmV0L3NjcmlwdHMvYi9haS4yLm1pbi5qc1wiLFxuICAgICAgY2ZnOiB7XG4gICAgICAgIGluc3RydW1lbnRhdGlvbktleTogXCIxMjM0NTY3ODkwXCIsXG4gICAgICAgIGVuYWJsZVVuaGFuZGxlZFByb21pc2VSZWplY3Rpb25UcmFja2luZzogZmFsc2UsXG4gICAgICB9LFxuICAgIH0pOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUtZWxzZS1pZiI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW1wb3J0LWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZXR0ZXItcmV0dXJuIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJlbnYiOnt9fX0=

**Comment by MSNev** [comment]
Ok, I think I found the issue I'll fix and create a v5 of the snippet -- It's unlikely to fix all of the eslint issues though.

**Comment by jwlawrence** [comment]
@MSNev I tried your v5 snippet and it works, thank you! Once that's merged I think we can close this ticket, though you might want to make a couple tickets to update documentation:

- https://docs.microsoft.com/en-us/azure/azure-monitor/app/usage-overview#send-telemetry-from-your-app
- https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#snippet-based-setup

**Comment by MSNev** [comment]
Tagging as "fixed" waiting release even though strictly speaking the snippet can be used as is from the readme
This is more for release tracking when we go to create the release notes.

**Comment by MSNev** [comment]
CDN Deployment rolled back due to #1452
