### ISSUE TITLE
[BUG] Angular 6 | Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by danouche93** [microsoft/ApplicationInsights-JS#1477]
**Description/Screenshot**
I use Angular 6 and I integrated the plugin to my project. All is going well, I receive the errors to App Insight but when my project builds I have all the time this error when app insight is initializing 
![image](https://user-images.githubusercontent.com/50110805/108339677-64a3c700-71e0-11eb-8231-f35801d7bced.png)

**Steps to Reproduce**

My package.json :
```
{
  "name": "tina-web-new",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.7",
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@microsoft/applicationinsights-angularplugin-js": "^2.5.10",
    "@microsoft/applicationinsights-web": "^2.4.4",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "@ng-select/ng-select": "^2.12.1",
    "@types/googlemaps": "^3.26.15",
    "auth0-js": "^9.13.4",
    "core-js": "^2.5.4",
    "jquery": "^3.5.1",
    "ngx-bootstrap": "^3.0.1",
    "ngx-image-cropper": "^2.0.2",
    "ngx-pagination": "^5.0.0",
    "ngx-spinner": "^7.0.0",
    "rxjs": "~6.2.0",
    "toastr": "^2.1.4",
    "xlsx": "^0.16.8",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.9",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}
```

My Appcomponent.ts :

```
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApplicationInsights } from '@microsoft/applicationinsights-web';
import { AngularPlugin, AngularPluginService } from '@microsoft/applicationinsights-angularplugin-js';

@Component({
  selector: 'body',
  template: '<ngx-spinner bdColor = "rgba(51, 51, 51, 0.8)" size="medium" color ="#fff" type="ball-spin-fade"></ngx-spinner><router-outlet></router-outlet>',
})
export class AppComponent implements OnInit {
  title = 'TinaWebNew';

  private appInsights;
    constructor(
        private router: Router,
        private angularPluginService: AngularPluginService 
    ){
        var angularPlugin = new AngularPlugin();
        this.angularPluginService.init(angularPlugin, this.router);
        this.appInsights = new ApplicationInsights({ config: {
        instrumentationKey: 'MyKey',
        extensions: [angularPlugin],
        extensionConfig: {
            [angularPlugin.identifier]: { router: this.router }
        },
        } });
    }

    ngOnInit() {
        this.appInsights.loadAppInsights();
    }
} 
```

**Expected behavior**

The project builds without errors.

**Comment by MSNev** [comment]
Hey, we will be releasing an updated version of the angular plugin shortly -- but I'm not sure that it will address this issue.

Internally, we don't call Object.deepExtend(), so it it possible for you to help by attempting to use the unminified version and debug (somehow) to identify which object that the deepExtend is recusing on.

Searching online, it doesn't appear to be specific to App Insights
https://stackoverflow.com/questions/25028597/how-can-i-fix-maximum-call-stack-size-exceeded-angularjs
https://github.com/angular/angular-cli/issues/17106

**Comment by danouche93** [comment]
It must be because of the plugin, I've never had this error before integrating it.
I tried to put angularPlugin.init() function in comment and the error is gone.

**Comment by MSNev** [comment]
@xiao-lix Can you see if you can repro when you get a chance, with the old and refactored version.

**Comment by xiao-lix** [comment]
Hi, @danouche93 sorry for the confusion but the angularPluginService was not properly implemented and we removed it from the next released version (will release soon). Can you try removing it from constructor and see if it fixes the issue? I can't reproduce the error locally even with it though. Also, I updated the doc that you may not notice, can you call loadAppInsights right after instantiate it inside the constructor? Thanks.

**Comment by danouche93** [comment]
Thank you for the fast response. Unfortunately your solution didn't help the problem :(
But I think where the problem is from. In my project I use an authService from auth0-js plugin. When I first login to the project, I don't have the error but when I'm already logged in and refresh the page, the error is shown. Somehow the refresh token of auth0 causes the problem to your plugin.

**Comment by xiao-lix** [comment]
@danouche93 we just released a new version of angular plugin, can you try to upgrade and see if that solves your problem though I'm not sure yet how auth0 causes the issue as you described. https://github.com/microsoft/applicationinsights-angularplugin-js

**Comment by danouche93** [comment]
I did the update and try to rebuild again with the changes. Unfortunately, the problem still remains and I have also warnings now.

![image](https://user-images.githubusercontent.com/50110805/108826675-43bae780-75cd-11eb-9890-fa595dc676e4.png)

**Comment by xiao-lix** [comment]
@danouche93 sorry to hear that. Do you have a test app / demo that reproduces this issue?

**Comment by danouche93** [comment]
I don't have a demo that I can show you the issue but if you do a project with Angular 6 with an authentication system with auth0 you can see the issue.

**Comment by danouche93** [comment]
I've just noticed that I don't receive at all the errors in app insight. I just have the real error "Uncaught RangeError" displaying.
I put a `throw new Error()` in one of my component but it is not displayed in app insight azure.

**Comment by xiao-lix** [comment]
@danouche93 I'm not familiar with auth0 but I did some searching. Looks like [this ](https://auth0.com/docs/libraries/auth0-angular-spa) package is what you should use for angular app? And it says the SDK is compatible with Angular SPAs version 9+ and above. I tested this [sample ](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) with Angular 11 and AI angular plugin 2.5.11 with no issue. 
For the other issue you don't see exception items, thanks for pointing it out. Since Angular is warping all exceptions in their own way and provide a global [error handler](https://pusher.com/tutorials/error-handling-angular-part-1) that intercepts all the errors, looks like the AI window.onerror hooks is never called. That would be some nice feature we could add in the future release. Thanks.

**Comment by xiao-lix** [comment]
Hello @danouche93 , I just released a new version of the angular plugin that adding the uncaught exception tracking feature: https://github.com/microsoft/applicationinsights-angularplugin-js/releases/tag/2.6.2 thanks.

**Comment by danouche93** [comment]
@xiao-lix I did the 2.6.2 update and now I got this error
 `ERROR in node_modules/@microsoft/applicationinsights-angularplugin-js/lib/applicationinsights-angularplugin-error.service.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.`

And it failed to compile.

**Comment by xiao-lix** [comment]
hi @danouche93, can you please try this [option](https://stackoverflow.com/questions/60131331/error-ts1086-an-accessor-cannot-be-declared-in-an-ambient-context-in-angular-9): 
```
"compilerOptions": {
   "skipLibCheck": true,
},
```
Please [note](https://github.com/microsoft/applicationinsights-angularplugin-js#note), Angular plugin is using newer version of typescript and [is NOT es3 compatible](https://github.com/microsoft/applicationinsights-angularplugin-js#microsoft-application-insights-javascript-sdk---angular-plugin). The issue is the version of TypeScript you are using (v2.9.2 -- based on the provided package.json) and the version of tslib that you are using. 
If this doesn't solve your issue, can you please provide a simplified repro as we are unable to repro your exact issue. And it would be also helpful if you could provide a copy of your tsconfig.json file. This error will occur if you are targetting es3. Thanks.

**Comment by fulvi0** [comment]
+1

I'm facing the same issue as @danouche93 

```bash
ERROR in node_modules/@microsoft/applicationinsights-angularplugin-js/lib/applicationinsights-angularplugin-error.service.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.
```
