### ISSUE TITLE
trackDependencyData() TS signature is not clear

### ISSUE THREAD

**Issue by JRGranell** [microsoft/ApplicationInsights-JS#929]
Upgrading the v2 I am trying to update our manual dependency tracking, however it is not clear what the call signature should be.

- the readme at https://github.com/microsoft/ApplicationInsights-JS
<img width="1090" alt="Screenshot 2019-06-11 at 08 57 23" src="https://user-images.githubusercontent.com/9625257/59253932-2abaa900-8c27-11e9-8063-6cd48f41fdf8.png">
- docs at https://github.com/microsoft/ApplicationInsights-JS/blob/329d77b15250ae8dfa25b86eae0146a65422a62b/vNext/AISKU/API.md is the same
<img width="1080" alt="Screenshot 2019-06-11 at 08 58 13" src="https://user-images.githubusercontent.com/9625257/59253975-3c9c4c00-8c27-11e9-8127-0533446b7c12.png">

However the typescript typings in code is

<img width="489" alt="Screenshot 2019-06-11 at 08 58 28" src="https://user-images.githubusercontent.com/9625257/59254012-49b93b00-8c27-11e9-974d-d51bec8723b9.png">

Which I assume is correct for the server side calls. At the moment I'm using `any` to cast the call to `appInsights.trackDependencyData()`.

**Comment by markwolff** [comment]
Only id is actually required for the item to be accepted, but as many fields should be set as possible so that the telemetry is actually useful. I will update the docs to account for a useful bare minimum (`id` + `responseCode`)

**Comment by JRGranell** [comment]
@markwolff thanks for updating the docs, the primary issue I faced is with the Typescript interfaces not being correct so my code wouldn't compile without the use of `any`.

**Comment by markwolff** [comment]
@JRGranell actually I believe this is because the docs incorrectly reference `resultCode`. Use `responseCode` instead. I've updated the docs to account for this as well!

**Comment by JRGranell** [comment]
Hi @markwolff thanks for the updated link, sorry to continue on this, I believe it may be a TypeScript definition or importing issue. Within the `applicationinsights-common` package `IDependencyTelemetry` is defined as 
```
{
    id: string;
    name?: string;
    duration?: number;
    success?: boolean;
    responseCode: number;
    correlationContext?: string;
    type?: string;
    data?: string;
    target?: string;
    properties?: {
        [key: string]: any;
    };
    measurements?: {
        [key: string]: number;
    };
}
```
https://github.com/microsoft/ApplicationInsights-JS/blob/9879276b5a3951d3187de91d9575bfb354aa6e25/vNext/shared/AppInsightsCommon/src/Interfaces/IDependencyTelemetry.ts

and can be imported from
```
import {
    ApplicationInsights,
    IDependencyTelemetry,
} from '@microsoft/applicationinsights-web';
```

I initialise using 
```
const ai = new ApplicationInsights({
            config: {
               ...
            }
        });
```

and the issue is when I try to do 

```
ai.trackDependencyData({
            id,
            method,
            absoluteUrl,
            duration,
            success,
            responseCode,
            properties,
            measurements
        });
```

An example error would be`'method' does not exist on type IDependencyTelemetry`. Is it possible the exported type from `web` is using the server side version?

Many thanks for continuing to look into this.

**Comment by BuZZ-T** [comment]
Sorry to comment in a closed issue, but i think the mismatch still occurs:
https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackdependencydata
vs.
https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IDependencyTelemetry.ts

E.g. the field "method" is not part of the interface.
Can this issue be reopened?

**Comment by MSNev** [comment]
https://github.com/microsoft/ApplicationInsights-JS/blob/master/extensions/applicationinsights-dependencies-js/src/ajaxRecord.ts#L329-L340
