### ISSUE TITLE
Regression in v2: "Field 'name' on type 'RemoteDependencyData' is too long" with long URL

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/ApplicationInsights-JS#930]
Seems issue #369 came back in v2... seeing a lot of these in SharePoint Online when using the OOTB AI JS v2 SDK:

**Field 'name' on type 'RemoteDependencyData' is too long. Expected: 1024 characters, Actual: 1242**

![image](https://user-images.githubusercontent.com/2068657/59279322-bc2f1880-8c31-11e9-98a8-92c4ba9d97c5.png)

**Comment by markwolff** [comment]
I've fixed this in #933 which will land in 2.0.2

**Comment by ecezalp** [comment]
Hello! I am still having this problem! My config is almost identical to [this example](https://stackoverflow.com/questions/56658326/field-name-on-type-remotedependencydata-is-too-long), and my dependencies are as follows: 

```
"@microsoft/applicationinsights-react-js": "^2.0.2", 
"@microsoft/applicationinsights-web": "^2.0.1", 
```
Would really appreciate some help. Thank you!

**Comment by markwolff** [comment]
Hi @ecezalp 2.0.2 hasn't shipped yet, but for now you can add a (non-breaking) telemetry initializer in the meantime
```js
appInsights.addTelemetryInitializer(item => {
    if (item.baseType === 'RemoteDependencyData') {
        if (item.baseData.name.length > 1024) {
            item.baseData.name = item.baseData.name.substring(0, 1024);
        }
    }
});
```
